# This is a workflow file that will be used to merge branches in the repository.
# Permissions required: 
#   Content 
#     write
#   Pull requests 
#     write

# Event data: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call received is equal to the caller event data. 
# In order to understand which version of script needs to be used parameter script version introduced, which should be equal to the ref of referenced workflow file.
# More information on the script_version:
#   https://github.com/orgs/community/discussions/18601
#   https://github.com/orgs/community/discussions/63863

on:
  workflow_call:
    inputs:      
      base_branch:
        type: string
        required: true
      allowAutomatedCommits:
        type: boolean
        required: false
        default: false
      quietComments:
        type: boolean
        required: false
        default: true
      script_version:
        type: string
        required: false
        default: 'main'

jobs:
  run-merge:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: repository
          fetch-depth: 0
      - name: Checkout arcade repository
        uses: actions/checkout@v4
        with:
          repository: f-alizada/arcade # will be replaced with dotnet: dotnet/arcade
          path: arcade-repository 
          ref: ${{ inputs.script_version }} # will be replaced with main

      - name: Print GitHub workflow ref
        run: echo "${{ toJSON(github.workflow_ref) }}"

      - name: Print GitHub ref name
        run: echo $env:GITHUB_REF_NAME

      - name: Switch parameters setting
        id: switch-parameters
        run: | 
          $mergeSwitchArguments = ""

          if ('${{ inputs.allowAutomatedCommits }}' -eq 'true') {
            $mergeSwitchArguments = "-AllowAutomatedCommits"
          }else{
            Write-Host "AllowAutomatedCommits is set to False"
          }

          if ('${{ inputs.quietComments }}' -eq 'true') {
            $mergeSwitchArguments = $mergeSwitchArguments + " -QuietComments"
          }else{
            Write-Host "QuietComments is set to False"
          }

          "mergeSwitchArguments=$mergeSwitchArguments" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Fetch repository name
        id: fetch-repo-name
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Repository name: ${{ github.repository }}"
          $repoName = "${{ github.repository }}"
          $repoNameWithoutOwner = $repoName.Substring("${{ github.repository_owner }}".Length + 1)
          "repository_name=$repoNameWithoutOwner" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - run: ${{ github.workspace }}\arcade-repository\.github\workflows\scripts\inter-branch-merge.ps1 -RepoName ${{ steps.fetch-repo-name.outputs.repository_name }} -RepoOwner ${{ github.repository_owner }} -HeadBranch $env:GITHUB_REF_NAME -BaseBranch ${{ inputs.base_branch }} ${{ steps.switch-parameters.outputs.mergeSwitchArguments }}
        name: Merge branches
        working-directory: ${{ github.workspace }}/repository